### PR TITLE
fix clean-css

### PR DESCRIPTION
**Pull request by yorkie**
Found another :) @jwu

### CODE REVIEW

**Comment by jwu** [comment]
How do you find out these missing modules? Even i don't have them explicitly, i still can run the program without require error.

**Comment by yorkie** [comment]
```json
"dependencies": {
  "electron-dockable": "^0.9.3",
  "electron-protocols": "^1.0.4",
  "lodash": "^4.17.4"
}
```

The above is my dependencies tree, you might install these modules in your root project :)

**Comment by jwu** [comment]
em...... I use a similar dependencies in another project, but didn't raise the error. Is it possible that I am using `yarn install` which hide the problem?

**Comment by yorkie** [comment]
@jwu Could you please `require` successfully in an zero environment like travis or cycle? Or you could try with:

```js
require.resolve('clean-css');
```

And see what paths you are using :)

**Pull request merged**
